### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShotDead7297** [corytortoise/PvPLevels#11]
hi how long does it take for the leaderboard to update

**Comment by corytortoise** [comment]
At the moment it only updates when a player joins or the server restarts. I intend to add the ability to make it update both by command and on a timer.

**Comment by ShotDead7297** [comment]
well can u add that then and it only updates when the server restarts

**Comment by YHC2538** [comment]
Update on timer will be nice. 

For ex. You can add a command called /pvptext update

Then, we can use the TimeCommander plugin by LDX and make it update every minute.

**Comment by ShotDead7297** [comment]
yes i agree

**Comment by corytortoise** [comment]
This should be resolved in the latest commit. Feel free to test it out.
