### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by samuelctn** [corytortoise/PvPLevels#13]
after restart the floating text it s gone
the delete thing doesnt works , give's an error

**Comment by corytortoise** [comment]
Can I see the error?

**Comment by samuelctn** [comment]
http://prntscr.com/kd9szr on join error
after restart the floating texts are gone.
they re not updating
if a player wasnt online when i placed the floating he cant see it only if i place it when he is also online
and error on pvptext delete http://prntscr.com/kd9ti9

**Comment by corytortoise** [comment]
Which version of PMMP are you running?

**Comment by samuelctn** [comment]
3.0.8

**Comment by corytortoise** [comment]
Thanks, I'll update you when I fix it.
