### ISSUE TITLE
Username with space

### ISSUE THREAD

**Issue by YHC2538** [corytortoise/PvPLevels#15]
Hello, 

There's an error that runs the command incorrectly when the target player's username has space in it. For example, here is my config of the 1st Level: 

```
1:
  kills: 1
  commands: 
  - "setprefix %p §e%l"
```

What this does with my PureChat plugin configuration, should set the target player's prefix chat like this:

`Lv. 1 Player123 God > Hi`

But instead, it shows this:

`God Lv.1 Player123 God > Hi`
It added the 2nd part of the username into the prefix.

After getting the error, I tried using escape characters like quotation marks like I do when running commands for space usernames: 

`- "setprefix "%p" §e%l"`
And this:
`- "setprefix \"%p\"  §e%l"`

But it gave me this error:
`[19:56:23] [Server thread/CRITICAL]: ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected key
`

How can I make the prefix work?

**Comment by corytortoise** [comment]
Which version of PureChat are you using? The latest one from poggit-orphanage should send a message when PvPLevels tries to run setprefix, because only players can run that command. This is something I hadn't thought of, so I'll take a look at it.

**Comment by YHC2538** [comment]
The prefix works perfectly for the player's name that has no space in it, only for the others that have space. 

And yes I am using the latest version of PureChat

**Comment by corytortoise** [comment]
Did you get the parsing error for both the quotations and the escape attempts?

**Comment by YHC2538** [comment]
Yes

**Comment by corytortoise** [comment]
Does the setprefix command work in-game if you use the quotation marks around names with spaces, as you mentioned?

**Comment by YHC2538** [comment]
Yes, that works perfectly in game when I use quotation marks around names with spaces

**Comment by dev4uhelp** [comment]
could you add top

**Comment by dev4uhelp** [comment]
top points or point each kill

**Comment by corytortoise** [comment]
That already exists. /pvptext kills spawns a leaderboard.

**Comment by dev4uhelp** [comment]
points each kill?

**Comment by corytortoise** [comment]
It counts the kills, but it doesn't have any kind of point system, aside from levels. That's not what this plugin is for.

**Comment by YHC2538** [comment]
Any updates for the fix? @corytortoise

**Comment by corytortoise** [comment]
I have a plan to fix it, but I've just started college(university, depending on where you live) and am very busy. I'll try to apply the fix soon.

**Comment by YHC2538** [comment]
Alright, thank you!

**Comment by YHC2538** [comment]
Oops

**Comment by YHC2538** [comment]
How's the progress of the fix?

**Comment by MSG100TC** [comment]
@corytortoise

**Comment by YHC2538** [comment]
Have you worked out a solution yet?

**Comment by corytortoise** [comment]
Unfortunately, I no longer have access to a server to test. I can push changes to a development branch, I suppose. Either way, it should be finished soon.

**Comment by corytortoise** [comment]
If you want, you can try the latest commit. Disclaimer: It probably doesn't work.

**Comment by YHC2538** [comment]
Hi, do you mean setting it to

1:
  kills: 1
  commands: 
  - "setprefix "/%p/" §e%l"

Or ?
1:
  kills: 1
  commands: 
  - "setprefix "%p" §e%l"

**Comment by corytortoise** [comment]
The way I set it up, it should be unnecessary for you to do anything other than just %p in the config. It should handle the name correctly, whether it's a single word or multiple.

**Comment by corytortoise** [comment]
Has this fixed your problem? I can't exactly test this, since I don't have a gamertag with a space in it.
