### ISSUE TITLE
Issue with creating pvptext

### ISSUE THREAD

**Issue by timbersquirrel** [corytortoise/PvPLevels#17]
I can’t create pvptext it says “unknown error occurred” please fix (3.0 api)

**Comment by corytortoise** [comment]
Send me the error printed to the server console.

**Comment by timbersquirrel** [comment]
30.08 19:27:15 [Server] Server thread/CRITICAL Unhandled exception executing command 'pvptext kdr' in pvptext: Call to a member function addParticle() on null
30.08 19:27:15 [Server] Server thread/CRITICAL Error: "Call to a member function addParticle() on null" (EXCEPTION) in "PvPLevels_dev-17.phar/src/corytortoise/PvPLevels/Main" at line 59
30.08 19:27:15 [Server] Server thread/DEBUG #0 PvPLevels_dev-17.phar/src/corytortoise/PvPLevels/Main(164): corytortoise\PvPLevels\Main->createText(pocketmine\math\Vector3 object, string kdr, NULL )
30.08 19:27:15 [Server] Server thread/DEBUG #1 src/pocketmine/command/PluginCommand(58): corytortoise\PvPLevels\Main->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string pvptext, array Array())
30.08 19:27:15 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string pvptext, array Array())
30.08 19:27:15 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1955): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string pvptext kdr)
30.08 19:27:15 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2191): pocketmine\Server->dispatchCommand(pocketmine\Player object, string pvptext kdr)
30.08 19:27:15 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /pvptext kdr)
30.08 19:27:15 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
30.08 19:27:15 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
30.08 19:27:15 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
30.08 19:27:15 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
30.08 19:27:15 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3056): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
30.08 19:27:15 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(162): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
30.08 19:27:15 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 174.20.48.248 50489, raklib\protocol\EncapsulatedPacket object, integer 0)
30.08 19:27:15 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
30.08 19:27:15 [Server] Server thread/DEBUG #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
30.08 19:27:15 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
30.08 19:27:15 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
30.08 19:27:15 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
30.08 19:27:15 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2259): pocketmine\snooze\SleeperHandler->sleepUntil(double 1535671635.5571)
30.08 19:27:15 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()
30.08 19:27:15 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1700): pocketmine\Server->start()
30.08 19:27:15 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
30.08 19:27:15 [Server] Server thread/DEBUG #22 /custom.phar(1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)

**Comment by timbersquirrel** [comment]
never mind i fixed
