### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by ShotDead7297** [corytortoise/PvPLevels#20]
27.10 16:49:28 [Server] Server thread/CRITICAL Unhandled exception executing command 'pvptext kills' in pvptext: Call to a member function addParticle() on null
27.10 16:49:28 [Server] Server thread/CRITICAL Error: "Call to a member function addParticle() on null" (EXCEPTION) in "PvPLevels-master/src/corytortoise/PvPLevels/Main" at line 63
27.10 16:49:28 [Server] Server thread/DEBUG #0 PvPLevels-master/src/corytortoise/PvPLevels/Main(176): corytortoise\PvPLevels\Main->createText(pocketmine\math\Vector3 object, string kills, NULL )
27.10 16:49:28 [Server] Server thread/DEBUG #1 src/pocketmine/command/PluginCommand(58): corytortoise\PvPLevels\Main->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string pvptext, array Array())
27.10 16:49:28 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string pvptext, array Array())
27.10 16:49:28 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1955): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string pvptext kills)
27.10 16:49:28 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2191): pocketmine\Server->dispatchCommand(pocketmine\Player object, string pvptext kills)
27.10 16:49:28 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(226): pocketmine\Player->chat(string /pvptext kills)
27.10 16:49:28 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
27.10 16:49:28 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(96): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
27.10 16:49:28 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
27.10 16:49:28 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(96): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
27.10 16:49:28 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3056): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
27.10 16:49:28 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(161): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
27.10 16:49:28 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 174.200.16.38 10639, raklib\protocol\EncapsulatedPacket object, integer 0)
27.10 16:49:28 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()
27.10 16:49:28 [Server] Server thread/DEBUG #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
27.10 16:49:28 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
27.10 16:49:28 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
27.10 16:49:28 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
27.10 16:49:28 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2259): pocketmine\snooze\SleeperHandler->sleepUntil(double 1540658968.2506)
27.10 16:49:28 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()
27.10 16:49:28 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1700): pocketmine\Server->start()
27.10 16:49:28 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
27.10 16:49:28 [Server] Server thread/DEBUG #22 /pmmp_1573_1.7.0.phar(1): require(string phar:///pmmp_1573_1.7.0.phar/src/pocketmine/PocketMine.php)

**Comment by corytortoise** [comment]
Check your config.yml. Either you haven't set the world name correctly, or you don't have an updated config. If yours doesn't have [this section](https://github.com/corytortoise/PvPLevels/blob/master/resources/config.yml#L6-L17), I suggest updating it by deleting the existing one and restarting your server. The plugin will then create a new, working one. You can copy your list of levels, if you don't want to lose them.
